### PR TITLE
Improved windows.rs docs

### PR DESCRIPTION
**Pull request by daniellga**
Made it clear the windows are periodic, as discussed in #46 .

### CODE REVIEW

**Comment by HEnquist** [comment]
I'm not sure this is the way to go. It's not only the windows that are periodic, the sincs are too. So the documentation should at least mention it in more places. 
But then again, both the the window functions and sincs are only used internally. They are not made to be used separately, and for a library user it should not matter if they are periodic or not. Mentioning it indicates that it's somehow important to know, which I'm worried may just confuse people.

**Comment by daniellga** [comment]
Another approach would be documenting this directly on the function which creates the windows (see example below), instead of documenting the enum directly. So the documentations would only be accessible when viewing the source code. Other suggestion is maybe put in the docs the equation used to generate these windows (more complex docs but more complete as well)... It's your call, no problem if you want to leave as it is right now. I just remembered of this since I came back to work on my package again after a long time.

```
/// Helper function. Standard Blackman-Harris window
pub fn blackman_harris<T>(npoints: usize) -> Vec<T>
```

**Comment by HEnquist** [comment]
Yes placing it as comments in the functions makes a lot more sense. That keeps it hidden from those that don't need to know, and accessible to those that do (assuming that they are looking at the code, feels like a pretty safe assumption!)
Drifting a little off topic now.. would it make sense to break the windows and sinc stuff out as a separate crate?

**Comment by daniellga** [comment]
Ok, I will modify this PR when I get some time so you can review it.
About the separate crate, I think if you intend to expand on the concept it would be a nice thing to do. For example, implement more window types, give the user the option to create a symmetric or periodic window, etc... I would definitely use it and I volunteer to help.

**Comment by daniellga** [comment]
Closing. See #67 .

**Comment by HEnquist** [comment]
Just got back to this, here is the WIP new crate for the window functions: https://github.com/HEnquist/windowfunctions-rs

**Comment by daniellga** [comment]
Nice! I got some window functions in the same style you did yours in rubato. Feel free to copy them if you think they are useful.

https://github.com/daniellga/harmonium/blob/master/harmonium-window/src/windows.rs

**Comment by HEnquist** [comment]
Thanks, I have copied a few now and will probably take a few more. There are so many window functions in the world that it's impossible to implement them all, but how to know when you have enough? :)

**Comment by HEnquist** [comment]
Published here: https://crates.io/crates/windowfunctions

**Pull request closed without merging**
