### PR TITLE
Allocatebug

### PR DESCRIPTION
**Pull request by HEnquist**
Fix bug and optionally let allocate methods pre-fill buffers.

### CODE REVIEW

**Comment by AlexTMjugador** [comment]
Is there anything blocking this PR? I'm affected by the regression on `output_buffer_allocate`, as its result no longer works with `process_into_buffer` as intended. I wouldn't mind helping.

**Comment by AlexTMjugador** [comment]
Also, [`output_frames_max`](https://docs.rs/rubato/0.13.0/rubato/trait.Resampler.html#tymethod.output_frames_max) does not return a correct upper frames bound at least for the `FftFixedIn` resampler when `nbr_chunks_ready` > 1. This happened on v0.13 too, but previously the buffer was just reallocated, which means that relying on the return value of `output_buffer_allocate`/`output_frames_max` to avoid allocations has never been effective, but that is now exacerbated due to the latest changes.

**Comment by HEnquist** [comment]
I thought it was ready and I was planning to release it as soon as I had some free time. But if there is an issue with `output_frames_max` then there is still work to do.
Can you open a new issue for that, with a simple example for how to trigger the problem?

**Comment by AlexTMjugador** [comment]
Sure, I can try to cobble together a reproduction case! Thank you for your effort in maintaining this library by the way :smile:

**Pull request merged**
